apiVersion: v1
kind: Namespace
metadata:
  name: llm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-prompt
  namespace: llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-prompt
  template:
    metadata:
      labels:
        app: llm-prompt
    spec:
      containers:
      - name: llm-prompt
        image: llm-prompt-local:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: OLLAMA_URL
          value: "http://ollama.ollama.svc.cluster.local:11434"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: llm-prompt
  namespace: llm
spec:
  type: NodePort
  selector:
    app: llm-prompt
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      name: http